version: '3'
services:
  node-app:
    image: node:latest
    container_name: node-app
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: cccat3_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
